OpenLiberty/guide-microprofile-rest-client

- README.adoc
Reviewing text on the line-by-line level.
> ID line edits

- finish/src/main/java/io/openliberty/guides/inventory/InventoryManager.java
- finish/src/main/java/io/openliberty/guides/inventory/InventoryResource.java
- finish/src/main/java/io/openliberty/guides/inventory/model/InventoryList.java
- finish/src/main/java/io/openliberty/guides/inventory/model/SystemData.java
- start/src/main/java/io/openliberty/guides/inventory/InventoryResource.java
- start/src/main/java/io/openliberty/guides/inventory/model/InventoryList.java
- start/src/main/java/io/openliberty/guides/inventory/model/SystemData.java
OpenLiberty/guides-common#95
OpenLiberty/guides-common#137
> Refactor inventory

- finish/src/main/java/io/openliberty/guides/inventory/InventoryManager.java
This fixes the code issue, but I'm not familiar with the .adoc processing.  Not sure if something needs adjustment there.
> Fixes issue #72; tolerate ConnectException

- README.adoc
- finish/src/main/java/io/openliberty/guides/inventory/InventoryManager.java
Addressing: https://github.com/OpenLiberty/guide-microprofile-rest-client/issues/72
- There is a UI change for this PR so we must coordinate with the ui team to refresh the site after merging
> Adding ConnectException, with formatting and hotspot changes

- README.adoc
to clarify where the base URL is specified and why it's used (Issue #85)
PR #86
> Merge qa to master: update readme 

- finish/pom.xml
- start/pom.xml
Issue:
OpenLiberty/guides-common#268
> Added dependencies

- finish/pom.xml
- start/pom.xml
Reduce the SRVE9967W warnings from the messages.log
#88
> Merge qa to master: Updating Dependencies

- README.adoc
- finish/pom.xml
- finish/src/main/liberty/config/server.xml
- start/pom.xml
- start/src/main/liberty/config/server.xml
> Merge qa to master: mp3 update

- README.adoc
- finish/src/main/java/io/openliberty/guides/inventory/InventoryManager.java
- finish/src/main/java/io/openliberty/guides/inventory/client/SystemClient.java
- finish/src/main/java/io/openliberty/guides/inventory/client/UnknownUriException.java
- finish/src/main/java/io/openliberty/guides/inventory/client/UnknownUriExceptionMapper.java
- finish/src/main/webapp/META-INF/microprofile-config.properties
* Updated to features in mp rest client 1.3
* More updates for mpRestClient 1.3
* Minor changes
* Formatted java classes
* Addressed dev content review feedback
* Addressed SME review feedback
* Added links for CDI and RestClientBuilder
* Minor changes
> Updated guide to MP Rest Client 1.3 (#97)

- README.adoc
> ID review feedback

- README.adoc
> Merge qa to master: update seo

- finish/pom.xml
- finish/src/main/webapp/index.html
- start/pom.xml
- start/src/main/webapp/index.html
> Merge qa to master: specify version directly in plugins

- finish/src/main/java/io/openliberty/guides/inventory/InventoryResource.java
- finish/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointIT.java
- start/src/main/java/io/openliberty/guides/inventory/InventoryResource.java
- start/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointIT.java
- addressed issues outlined here: https://github.com/OpenLiberty/guides-common/issues/243
> update error message

- finish/src/main/java/io/openliberty/guides/inventory/InventoryManager.java
- finish/src/main/java/io/openliberty/guides/inventory/model/SystemData.java
- start/src/main/java/io/openliberty/guides/inventory/model/SystemData.java
Addresses: https://github.com/OpenLiberty/guide-microprofile-rest-client/issues/57
> improve code

- finish/src/main/java/io/openliberty/guides/inventory/InventoryManager.java
- previous code change resulted in:
> fix wrapped line

- README.adoc
> Merge qa to master: add async guide to next

- README.adoc
- finish/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointIT.java
Added warning message thrown by test case and explaining that it is expected.
> Warning message

- .github/workflows/test.yml
> Merge qa to master: explain the warning from the test output

- .github/workflows/test.yml
- finish/pom.xml
- scripts/dailyBuild.sh
- scripts/testApp.sh
- start/pom.xml
Part of https://github.com/OpenLiberty/guides-common/issues/531
> Add daily build to GH Actions

- .github/workflows/test.yml
- finish/pom.xml
- scripts/dailyBuild.sh
- scripts/testApp.sh
- start/pom.xml
* update for daily build
* Update test.yml
* Update test.yml
* Update test.yml
Co-authored-by: Gilbert Kwan <gkwan@ca.ibm.com>
> Merge qa to master: Add daily build to GH Actions (#144)

- README.adoc
> Cloud hosted update

- README.adoc
* improved microservie descriptions
* update descriptions
* formatting for converter
* Update README.adoc
* ID review
* ID review
* ID review
Co-authored-by: Griffin Hadfield <griffhadfield@gmail.com>
Co-authored-by: YK Chang <yeekangc@ca.ibm.com>
> Merge qa to master: Cloud hosted update (#161)

- README.adoc
improve the cloud-hosted instructions
> Merge qa to master: Update README.adoc (#163)
